### ISSUE TITLE
Separate DateTime provider

### ISSUE THREAD

**Issue by Scogun** [Scogun/kcron-common#22]
### General Information
Right now we use [kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime) as multiplatform solution.
However, sometimes it make sense to use other DateTime provider.

### Possible Solution
We have to extract any work with LocalDateTime into injected abstract DateTimeProvider.
We also must extract the functionality without the kotlinx-datetime library into `kcron-common-core` library.
As default implementation we must keep `kcron-common` package which will use kotlinx-datetime as DateTime implementation.

**Comment by Scogun** [comment]
After some investigation, I found that there is no better KMP date-time library than [kotlinx-datetime](https://github.com/Kotlin/kotlinx-datetime).
So, maybe add the possibility to use different date-time provider is good but it should not reduce the current platforms amount.

**Comment by romualdbassinot** [comment]
Hi, in my case I would use you dependency in a JVM context, but without an other dependency like kotlinx-datetime as DateTime implementation. The JDK give already the java.time and I prefer to avoid to multiply dependency to do the same things.

**Comment by Scogun** [comment]
Hello @romualdbassinot!

Could you look into my PR?

**Comment by romualdbassinot** [comment]
Thanks I will look this week.
