### ISSUE TITLE
Could not find com.ucasoft.kcron:kcron-common-macosarm64:0.10.2

### ISSUE THREAD

**Issue by mgroth0** [Scogun/kcron-common#28]
I just discovered this library and think it would could be useful for me. Unfortunately, it does not resolve for native macosarm64:

```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.ucasoft.kcron:kcron-common-macosarm64:0.10.2.
```

It resolves fine for js, android and jvm. Only problem is with native.

I never had this issue with another kotlin library, so I think there might be something slightly unusual about how multiplatform artifacts are being published.

I dug a little deeper and noticed something interesting. If we look at kotlinx-io, which is a multiplatform module that works for me on all targets, and we look at its `.module` metadata file (example [here](https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-io-core/0.3.1/kotlinx-io-core-0.3.1.module)) we see that for "macosArm64ApiElements-published", there is this field:

```
"artifactType": "org.jetbrains.kotlin.klib"
```

And then if we look at the metadata from this library ([here](https://repo1.maven.org/maven2/com/ucasoft/kcron/kcron-common/0.10.2/kcron-common-0.10.2.module)) we see that this field does not exist. I do not know if this is the issue, it could be unrelated. But I hope this helps.

**Comment by Scogun** [comment]
Hello @mgroth0!
Thx to highlight the problem.
I think the problem is [here](https://github.com/Scogun/kcron-common/blob/main/.github/workflows/publish.yml#L16).
It should be like [these](https://github.com/Scogun/komm/blob/main/.github/workflows/publish.yml#L20).
I will fix it soon.
