### ISSUE TITLE
Enhancement Request: Support for ‘*’ Character in Day Fields, Similar to ‘?’

### ISSUE THREAD

**Issue by aitordiazdeotazu** [Scogun/kcron-common#33]
Hello,

I'd like to request a feature enhancement for the days field in the scheduling functionality. Currently, the '?' character is used to denote 'no specific value'. It would be highly beneficial if the '*' character could also be supported to represent 'every day' in a similar context.

This feature would align with the standard use of cron expressions, where '?' indicates a lack of a value, and '*' represents every possible value for a field. Implementing this would improve flexibility and intuitiveness for users configuring schedules.

Thank you for considering this addition.

Best regards,
Aitor

**Comment by Scogun** [comment]
Hello @aitordiazdeotazu!

Thank you for your message. Could you give a few examples with `?` and `*` using to make the request clearer?

**Comment by aitordiazdeotazu** [comment]
Hello @Scogun ,

According to [Crontab Guru](https://crontab.guru), the '?' symbol is not a standard for days field and may not be supported by many systems, whereas '*' is. Here are a couple of examples:

0 0 * * * - This cron expression will run the task every day at midnight.
0 0 ? * 2 - This expression might be intended to run a task every Tuesday at midnight, but '?' is not standard across all systems.

Adding support for '*' to function the same way as '?' would enhance compatibility with these systems.

Best regards,
Aitor

**Comment by Scogun** [comment]
Hello @aitordiazdeotazu,

Okay, I see. So, for classic expressions there should be `*` instead of `?`.
Hopefully, it won't take a long time.

Thank you, again!
